spec:
  replicas: 3
  template:
    metadata:
      labels:
        leader.election: "true"
    spec:
      serviceAccountName: "camel-leader-election"
      containers:
        - resources:
            requests:
              cpu: "0.2"
              memory: 128Mi
            limits:
              cpu: "1.0"
              memory: 512Mi